export const SET_CURRENT_VIDEOS = "SET_CURRENT_VIDEOS";
export const ADD_NEW_VIDEO = "ADD_NEW_VIDEO";
export const DELETE_VIDEO = "DELETE_VIDEO";
export const DELETE_ONE_VIDEO = "DELETE_ONE_VIDEO";
export const TOGGLE_VIEW_MODE = "TOGGLE_VIEW_MODE";
export const SET_CURRENT_VIDEO_ID = "SET_CURRENT_VIDEO_ID";
